# 🔗 Monitoring: Website Linkchecker
# ======================================================


---

name: 🔗 Website Linkchecker


# Driving Event
# -------------
#
# What event starts this workflow: a push to any branch other than main

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


# What to Do
# ----------
#
# Test the software with tox

jobs:
    linkcheck:
        name: 🔗 Linkcheck
        runs-on: ubuntu-latest
        if: github.actor != 'pdsen-ci'

        steps:
            -
                name: Set up Python 3
                uses: actions/setup-python@v5
                with:
                    python-version: '3.9'
            -
                name: 💵 Python Cache
                uses: actions/cache@v4
                with:
                    path: ~/.cache/pip
                    # The "key" used to indicate a set of cached files is the operating system runner
                    # plus "py" for Python-specific builds, plus a hash of the wheels, plus "pds" because
                    # we pds-prefix everything with "pds" in PDS! 😅
                    key: pds-${{runner.os}}-py-${{hashFiles('**/*.whl')}}
                    # To restore a set of files, we only need to match a prefix of the saved key.
                    restore-keys: pds-${{runner.os}}-py-
            -
                name: 🩺 Install and Run linkchecker
                id: checker
                run: |
                    pip3 install linkchecker

                    export XDG_DATA_HOME=$(pwd)
                    export LINKCHECKER_OUTDIR=${XDG_DATA_HOME}/linkchecker
                    echo "LINKCHECKER_OUTDIR=${LINKCHECKER_OUTDIR}" >> $GITHUB_OUTPUT
                    linkchecker --file-output=failures https://pds.nasa.gov

                    if [ -f ${LINKCHECKER_OUTDIR}/failures ]; then
                      exit 1
                    fi
                shell: bash

            - name: Upload linkchecker failure output
              uses: actions/upload-artifact@v4
              with:
                name: linkchecker-failures
                path: ${{ steps.checker.outputs.LINKCHECKER_OUTDIR }}
                if-no-files-found: ignore
              if: ${{ always() }}
